In [1]:
def scrap1_premier_league_stats():
    
    from bs4 import BeautifulSoup
    import requests

    url='https://fbref.com/en/comps/9/Premier-League-Stats'

    page = requests.get(url)

    soup = BeautifulSoup(page.text,'html')
    
    soup.find_all('table')[1]
    
    table = soup.find("table", class_ ="stats_table sortable min_width force_mobilize")
    
    table_titles=table.find_all('th')
    
    all_table_titles = [title.text for title in table_titles][1:20]
    
    import pandas as pd
    
    df = pd.DataFrame(columns = all_table_titles)
    
    column_data = table.find_all('tr')
    
    for row in column_data[1:]:
        row_data = row.find_all('td')[:19]
        individual_row_data = [data.text.strip() for data in row_data]
        lenght = len(df)
        df.loc[lenght]=individual_row_data
        
    df['Squad'].replace('Newcastle Utd','Newcastle',inplace = True)
    df['Squad'].replace('Sheffield Utd','Sheffield',inplace = True)
    df['Squad'].replace(df.iloc[12][0],'Nottingham Forest',inplace = True)
    df['Squad'].replace('Luton Town','Luton',inplace = True)
    df['xG'] = df['xG'].str.replace(r'\.', ',', regex=True)
    
    df.to_csv(r'C:\Users\zakv\Desktop\Data_analyst\PremierLeaguexG.csv',  index=False)
    
    print(df)

In [2]:
scrap1_premier_league_stats()

                Squad MP  W  D  L  GF  GA   GD Pts Pts/MP    xG   xGA    xGD  \
0           Tottenham  8  6  2  0  18   8  +10  20   2.50  15,0  10.8   +4.2
1             Arsenal  8  6  2  0  16   6  +10  20   2.50  14,9   6.5   +8.3
2     Manchester City  8  6  0  2  17   6  +11  18   2.25  14,9   5.5   +9.4
3           Liverpool  8  5  2  1  18   9   +9  17   2.13  16,8  11.5   +5.4
4         Aston Villa  8  5  1  2  19  12   +7  16   2.00  15,1  13.0   +2.0
5            Brighton  8  5  1  2  21  16   +5  16   2.00  16,5  13.8   +2.7
6            West Ham  8  4  2  2  15  12   +3  14   1.75  12,2  16.3   -4.1
7           Newcastle  8  4  1  3  20   9  +11  13   1.63  17,3   8.2   +9.1
8      Crystal Palace  8  3  3  2   7   7    0  12   1.50   8,9  10.6   -1.6
9      Manchester Utd  8  4  0  4   9  12   -3  12   1.50  12,6  12.1   +0.6
10            Chelsea  8  3  2  3  11   7   +4  11   1.38  15,0   8.1   +6.9
11             Fulham  8  3  2  3   8  13   -5  11   1.38   8,7  15.3   -6.6
12  Nottingham Forest  8  2  3  3   8  10   -2   9   1.13   7,8  10.8   -3.0
13             Wolves  8  2  2  4   9  14   -5   8   1.00   9,9  14.9   -5.1
14          Brentford  8  1  4  3  11  12   -1   7   0.88  13,8   9.8   +4.0
15            Everton  8  2  1  5   9  12   -3   7   0.88  14,7  10.2   +4.5
16              Luton  8  1  1  6   6  15   -9   4   0.50   9,5  14.7   -5.2
17            Burnley  8  1  1  6   7  20  -13   4   0.50   6,5  14.7   -8.2
18        Bournemouth  8  0  3  5   5  18  -13   3   0.38   8,8  18.6   -9.8
19          Sheffield  8  0  1  7   6  22  -16   1   0.13   6,1  19.6  -13.5

   xGD/90     Last 5 Attendance                       Top Team Scorer  \
0   +0.53  W W D W W     61,872                     Son Heung-min - 6
1   +1.04  W W D W W     60,105                       Bukayo Saka - 4
2   +1.17  W W W L L     35,437                    Erling Haaland - 8
3   +0.67  W W W L D     51,130                     Mohamed Salah - 5
4   +0.26  L W W W D     41,046                     Ollie Watkins - 4
5   +0.34  W W W L D     31,674                     Evan Ferguson - 4
6   -0.51  W L L W D     46,846                      Jarrod Bowen - 5
7   +1.14  L W W W D     51,945                    Alexander Isak - 6
8   -0.20  W L D W D     18,501                   Odsonne Édouard - 4
9   +0.07  L L W L W     73,485  Bruno Fernandes, Scott McTominay - 2
10  +0.86  L D L W W     39,877                   Raheem Sterling - 3
11  -0.83  L W D L W     24,377                        Bobby Reid - 2
12  -0.37  W D L D D     29,131                     Taiwo Awoniyi - 3
13  -0.64  L L D W D     23,497                    Hwang Hee-chan - 5
14  +0.50  D L L D L     17,004                      Bryan Mbeumo - 4
15  +0.56  D L W L W     39,222                Abdoulaye Doucouré - 3
16  -0.65  L D W L L     10,726                    Carlton Morris - 3
17  -1.02  D L L W L     17,301                       Lyle Foster - 3
18  -1.23  D D L L L     10,857                   Dominic Solanke - 3
19  -1.69  D L L L L     31,195                     Gustavo Hamer - 2

                       Goalkeeper Notes
0               Guglielmo Vicario
1      David Raya, Aaron Ramsdale
2                         Ederson
3                         Alisson
4               Emiliano Martínez
5   Jason Steele, Bart Verbruggen
6                 Alphonse Areola
7                       Nick Pope
8                   Sam Johnstone
9                     André Onana
10                 Robert Sánchez
11                     Bernd Leno
12                    Matt Turner
13                        José Sá
14                   Mark Flekken
15                Jordan Pickford
16                Thomas Kaminski
17                 James Trafford
18                           Neto
19                Wes Foderingham

In [3]:
def scrap2_premier_league_stats():
    
    from bs4 import BeautifulSoup
    import requests
    
    url='https://www.topscorersfootball.com/premier-league'

    page = requests.get(url)

    soup = BeautifulSoup(page.text,'html')
    
    soup.find_all('table')[1]
    
    table = soup.find("table", class_ ="table table-striped")
    
    table_titles=table.find_all('th')
    
    all_table_titles = [title.text for title in table_titles]
    
    import pandas as pd
    
    df = pd.DataFrame(columns = all_table_titles)
    
    column_data = table.find_all('tr')
    
    for row in column_data[1:]:
        row_data = row.find_all('td')
        individual_row_data = [data.text.strip() for data in row_data]
        lenght = len(df)
        df.loc[lenght]=individual_row_data

    df['Team'].replace('Sheffield United','Sheffield',inplace = True)
    df['Team'].replace('Manchester United','Manchester Utd',inplace = True)
    
    df.to_csv(r'C:\Users\zakv\Desktop\Data_analyst\PremierLeagueTopScores.csv',  index=False)
    
    print(df)

In [4]:
scrap2_premier_league_stats()

      #                Player               Team Age   Nationality  \
0    1.  Erling Braut Haaland    Manchester City  23        Norway
1    2.        Alexander Isak          Newcastle  24        Sweden
2               Son Heung-Min          Tottenham  31   South Korea
3    4.        Hwang Hee-chan      Wolverhampton  27   South Korea
4                Jarrod Bowen           West Ham  26       England
5               Mohamed Salah          Liverpool  31         Egypt
6    7.          Bryan Mbeumo          Brentford  24        France
7                 Bukayo Saka            Arsenal  22       England
8               Callum Wilson          Newcastle  31       England
9               Evan Ferguson           Brighton  18       Ireland
10            Odsonne Edouard     Crystal Palace  25        France
11              Ollie Watkins        Aston Villa  27       England
12  13.    Abdoulaye Doucouré            Everton  30        France
13             Carlton Morris              Luton  27       England
14               Darwin Núñez          Liverpool  24       Uruguay
15            Dominic Solanke        Bournemouth  26       England
16               Douglas Luiz        Aston Villa  25        Brazil
17             Julián Álvarez    Manchester City  23     Argentina
18               Kaoru Mitoma           Brighton  26         Japan
19                Lyle Foster            Burnley  23  South Africa
20            Martin Ødegaard            Arsenal  24        Norway
21             Mathias Jensen          Brentford  27       Denmark
22            Raheem Sterling            Chelsea  28       England
23                Solly March           Brighton  29       England
24              Taiwo Awoniyi  Nottingham Forest  26       Nigeria

   % team's goals Goals
0           47.1%     8
1           30.0%     6
2           33.3%     6
3           55.6%     5
4           33.3%     5
5           27.8%     5
6           36.4%     4
7           25.0%     4
8           20.0%     4
9           19.0%     4
10          57.1%     4
11          21.1%     4
12          33.3%     3
13          50.0%     3
14          16.7%     3
15          60.0%     3
16          15.8%     3
17          17.6%     3
18          14.3%     3
19          42.9%     3
20          18.8%     3
21          27.3%     3
22          27.3%     3
23          14.3%     3
24          37.5%     3

In [5]:
def scrap3_premier_league_stats():
    
    from bs4 import BeautifulSoup
    import requests
    
    url='https://www.topscorersfootball.com/premier-league'

    page = requests.get(url)

    soup = BeautifulSoup(page.text,'html')
    
    soup.find_all('table')[2]
    
    table = soup.find("table", class_ ="table table-striped table-small-font")
    
    table_titles=table.find_all('th')
    
    all_table_titles = [title.text for title in table_titles]
    
    import pandas as pd
    
    df = pd.DataFrame(columns = all_table_titles)
    
    column_data = table.find_all('tr')
    
    for row in column_data[1:]:
        row_data = row.find_all('td')
        individual_row_data = [data.text.strip() for data in row_data]
        lenght = len(df)
        df.loc[lenght]=individual_row_data
      
    df['Team'].replace('Sheffield United','Sheffield',inplace = True)
    df['Team'].replace('Manchester United','Manchester Utd',inplace = True)
    
    df.to_csv(r'C:\Users\zakv\Desktop\Data_analyst\PremierLeagueTable.csv',  index=False)
    
    print(df)

In [6]:
scrap3_premier_league_stats()

      #               Team Matches WinsW DrawsD LossesL  Goals Points
0    1.          Tottenham       8     6      2       0   18-8     20
1    2.            Arsenal       8     6      2       0   16-6     20
2    3.    Manchester City       8     6      0       2   17-6     18
3    4.          Liverpool       8     5      2       1   18-9     17
4    5.        Aston Villa       8     5      1       2  19-12     16
5    6.           Brighton       8     5      1       2  21-16     16
6    7.           West Ham       8     4      2       2  15-12     14
7    8.          Newcastle       8     4      1       3   20-9     13
8    9.     Crystal Palace       8     3      3       2    7-7     12
9   10.     Manchester Utd       8     4      0       4   9-12     12
10  11.            Chelsea       8     3      2       3   11-7     11
11  12.             Fulham       8     3      2       3   8-13     11
12  13.  Nottingham Forest       8     2      3       3   8-10      9
13  14.      Wolverhampton       8     2      2       4   9-14      8
14  15.          Brentford       8     1      4       3  11-12      7
15  16.            Everton       8     2      1       5   9-12      7
16  17.              Luton       8     1      1       6   6-15      4
17  18.            Burnley       8     1      1       6   7-20      4
18  19.        Bournemouth       8     0      3       5   5-18      3
19  20.          Sheffield       8     0      1       7   6-22      1